/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.view;
import edu.ijse.mvc.controller.CustomerController;
import edu.ijse.mvc.controller.ItemController;
import edu.ijse.mvc.dto.CustomerDto;
import edu.ijse.mvc.dto.ItemDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vinod
 */
public class customerView extends javax.swing.JFrame {

   private final CustomerController CUSTOMER_CONTROLLER;
    /**
     * Creates new form customerView
     */
    public customerView() {
        CUSTOMER_CONTROLLER=new CustomerController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        idLab = new javax.swing.JLabel();
        SalaryText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MissRadioButton = new javax.swing.JRadioButton();
        MrRadioButton = new javax.swing.JRadioButton();
        titleLab = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nameLab = new javax.swing.JLabel();
        PostalCodeLab = new javax.swing.JLabel();
        BirthYearCombo = new javax.swing.JComboBox<>();
        birthLab = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ProvinceText = new javax.swing.JTextField();
        addressLab = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        CityText = new javax.swing.JTextField();
        SalarayLab = new javax.swing.JLabel();
        PostalCodeText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BirthDayCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        BirthMonthCombo = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        MSRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Form");

        idLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idLab.setForeground(new java.awt.Color(0, 0, 102));
        idLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idLab.setText("Cust_id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Day");

        MissRadioButton.setForeground(new java.awt.Color(0, 0, 102));
        MissRadioButton.setText("Miss");
        MissRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissRadioButtonActionPerformed(evt);
            }
        });

        MrRadioButton.setForeground(new java.awt.Color(0, 0, 102));
        MrRadioButton.setText("Mr");
        MrRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrRadioButtonActionPerformed(evt);
            }
        });

        titleLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLab.setForeground(new java.awt.Color(0, 0, 102));
        titleLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLab.setText("Cust_title");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        nameLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLab.setForeground(new java.awt.Color(0, 0, 102));
        nameLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLab.setText("Cust_name");

        PostalCodeLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PostalCodeLab.setForeground(new java.awt.Color(0, 0, 102));
        PostalCodeLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PostalCodeLab.setText("Postal Code");

        BirthYearCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthYearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        BirthYearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthYearComboActionPerformed(evt);
            }
        });

        birthLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        birthLab.setForeground(new java.awt.Color(0, 0, 102));
        birthLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        birthLab.setText("Date of Birth");

        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Province");

        ProvinceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinceTextActionPerformed(evt);
            }
        });

        addressLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLab.setForeground(new java.awt.Color(0, 0, 102));
        addressLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressLab.setText("Address");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("City");

        AddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextActionPerformed(evt);
            }
        });

        CityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextActionPerformed(evt);
            }
        });

        SalarayLab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SalarayLab.setForeground(new java.awt.Color(0, 0, 102));
        SalarayLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SalarayLab.setText("Salary");

        PostalCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostalCodeTextActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Year");

        BirthDayCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthDayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", " 28", " 29", " 30", " 31" }));
        BirthDayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayComboActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Month");

        BirthMonthCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BirthMonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthComboActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 0, 0));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 102, 0));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(0, 204, 51));
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        MSRadioButton.setForeground(new java.awt.Color(0, 0, 102));
        MSRadioButton.setText("Ms");
        MSRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLab, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthLab)
                            .addComponent(addressLab, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostalCodeLab)
                            .addComponent(SalarayLab))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostalCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MrRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MissRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MSRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel10)
                                        .addGap(36, 36, 36)
                                        .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(ProvinceText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MrRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(MissRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MSRadioButton))
                    .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SalarayLab, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(SalaryText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ProvinceText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PostalCodeLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PostalCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(UpdateButton)
                    .addComponent(SaveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MissRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MissRadioButtonActionPerformed

    private void MrRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MrRadioButtonActionPerformed

    private void BirthYearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthYearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthYearComboActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void ProvinceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinceTextActionPerformed

    private void AddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextActionPerformed

    private void CityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextActionPerformed

    private void PostalCodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostalCodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostalCodeTextActionPerformed

    private void BirthDayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDayComboActionPerformed

    private void BirthMonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthComboActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try{
            String id=idText.getText();
            String result=CUSTOMER_CONTROLLER.deleteCustomer(id);
           if(result=="Success"){
               JOptionPane.showMessageDialog(this, "Customer deleted succusfully..");
           }
           
           else{
               JOptionPane.showMessageDialog(this, "Error occured,Customer id not found!");
           }
           loadTable(); 
        }
        
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        
        CustomerDto dto=new CustomerDto();
            dto.setCustID(idText.getText());
            dto.setCustTitle(groupingMethod());
            dto.setCustName(nameText.getText());
            dto.setDOB((String)BirthYearCombo.getSelectedItem()+"-"+(String)BirthMonthCombo.getSelectedItem()+"-"+(String)BirthDayCombo.getSelectedItem());
            dto.setSalary(Double.parseDouble(SalaryText.getText()));
            dto.setCustAddress(AddressText.getText());
            dto.setCity(CityText.getText());
            dto.setProvince(ProvinceText.getText());
            dto.setPostalCode(Integer.parseInt(PostalCodeText.getText()));
             
         try {
            String resp = CUSTOMER_CONTROLLER.updateCustomer(dto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }//GEN-LAST:event_UpdateButtonActionPerformed
public void clearForm(){
        idText.setText("");
        buttonGroup1.clearSelection();
        nameText.setText("");
        BirthDayCombo.setSelectedIndex(0);
        BirthMonthCombo.setSelectedIndex(0);
        BirthYearCombo.setSelectedIndex(0);
        SalaryText.setText("");
        AddressText.setText("");
        CityText.setText("");
        ProvinceText.setText("");
        PostalCodeText.setText("");
        
    }
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        try{
            CustomerDto dto=new CustomerDto();
            dto.setCustID(idText.getText());
            dto.setCustTitle(groupingMethod());
            dto.setCustName(nameText.getText());
            dto.setDOB((String)BirthYearCombo.getSelectedItem()+"-"+(String)BirthMonthCombo.getSelectedItem()+"-"+(String)BirthDayCombo.getSelectedItem());
            dto.setSalary(Double.parseDouble(SalaryText.getText()));
            dto.setCustAddress(AddressText.getText());
            dto.setCity(CityText.getText());
            dto.setProvince(ProvinceText.getText());
            dto.setPostalCode(Integer.parseInt(PostalCodeText.getText()));
            
            CUSTOMER_CONTROLLER.save(dto);
            loadTable();
            
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        searchCustomer();
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void MSRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MSRadioButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(customerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(customerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(customerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(customerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new customerView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressText;
    private javax.swing.JComboBox<String> BirthDayCombo;
    private javax.swing.JComboBox<String> BirthMonthCombo;
    private javax.swing.JComboBox<String> BirthYearCombo;
    private javax.swing.JTextField CityText;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JRadioButton MSRadioButton;
    private javax.swing.JRadioButton MissRadioButton;
    private javax.swing.JRadioButton MrRadioButton;
    private javax.swing.JLabel PostalCodeLab;
    private javax.swing.JTextField PostalCodeText;
    private javax.swing.JTextField ProvinceText;
    private javax.swing.JLabel SalarayLab;
    private javax.swing.JTextField SalaryText;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel addressLab;
    private javax.swing.JLabel birthLab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel idLab;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLab;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel titleLab;
    // End of variables declaration//GEN-END:variables

    private void loadTable(){
        try{
            String columns[] = {"CustID","CustTitle","CustName","DOB","salary","CustAddress","City","Province","PostalCode "};
            DefaultTableModel dtm;
            dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            ArrayList<CustomerDto> dtos= CUSTOMER_CONTROLLER.getAll();
          
          for(CustomerDto dto:dtos){
              Object[] rowData={dto.getCustID(),dto.getCustTitle(),dto.getCustName(),dto.getDOB(),dto.getSalary(),dto.getCustAddress(),dto.getCity(),dto.getProvince(),dto.getPostalCode()};
              dtm.addRow(rowData);
          }
          
          CustomerTable.setModel(dtm);
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }
    
    public String groupingMethod(){
       buttonGroup1.add(MrRadioButton);
       buttonGroup1.add(MissRadioButton);
       buttonGroup1.add(MSRadioButton);
       String resultText;
        if(MrRadioButton.isSelected()){
            resultText="Mr";
        }
        else if(MissRadioButton.isSelected()){
             resultText="Miss";
        }
        
        else if(MSRadioButton.isSelected()){
             resultText="Ms";
        }
        
        else{
            resultText="-";
        }
        
        return resultText;
    }
    
    private void searchCustomer() {
        String custId = (String) CustomerTable.getValueAt(CustomerTable.getSelectedRow(), 0);
        System.out.println(custId);

        try {

            CustomerDto custDto = CUSTOMER_CONTROLLER.searchCustomer(custId);
            if (custDto != null) {
                idText.setText(custDto.getCustID());
                setRadioButton(custDto.getCustTitle());
                setDOB(custDto.getDOB());
                nameText.setText(custDto.getCustName());
                SalaryText.setText(Double.toString(custDto.getSalary()));
                AddressText.setText(custDto.getCustAddress());
                CityText.setText(custDto.getCity());
                ProvinceText.setText(custDto.getProvince());
                PostalCodeText.setText(Integer.toString(custDto.getPostalCode()));
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
    private void setRadioButton(String title){
        if(title.equals("Mr")){
            MrRadioButton.setSelected(true);
            MissRadioButton.setSelected(false);
            MSRadioButton.setSelected(false);
        }
        
        else if(title.equals("Miss")){
            MissRadioButton.setSelected(true);
            MrRadioButton.setSelected(false);
            MSRadioButton.setSelected(false);
        }
        else if(title.equals("Ms")){
            MissRadioButton.setSelected(false);
            MrRadioButton.setSelected(false);
            MSRadioButton.setSelected(true);
        }
        else{
            MrRadioButton.setSelected(false);
            MissRadioButton.setSelected(false);
            MSRadioButton.setSelected(false);
        }
    }
    
    private void setDOB(String dob){
      String[] dobParts = dob.split("-");
      if (dobParts.length == 3) {
        String year = dobParts[0];  
        String month = dobParts[1]; 
        String day = dobParts[2];   

        BirthYearCombo.setSelectedItem(year);
        BirthMonthCombo.setSelectedItem(month);
        BirthDayCombo.setSelectedItem(day);
    } else {
        JOptionPane.showMessageDialog(this, "Invalid date format!");
    }
    }
}


